_defaults:
  - "_size_672.yml"
  - "_half.yml"
vanilla: true
model:
  backbone_config:
    block_config:
      merging_iterations: 3
      r_match: 0.5
      caching: true
      token_skip: true
      secondary: "none"
      secondary_keep: 0.5
